[package]
name = "codecrafters-git"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.94"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
const-hex = "1.19.1"
flate2 = { version = "1.0.34" } # features = ["zlib-ng"] }
sha1-checked = "0.10.0"

[[bench]]
name = "memory_bench"
harness = false

[[bench]]
name = "time_bench"
harness = false

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
iai-callgrind = "0.16.1"

[profile.bench]
debug = true
